spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: mall
    password: asd51735
  data:
    mongodb:
      host: mongo
      port: 27017
      database: mall-port
    redis:
      host: redis # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /mall
    username: mall
    password: asd51735
# 日志配置
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: logstash
alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: 9021000140641310
  alipayPublicKey: test # 自行查看nacos
  appPrivateKey: test # 自行查看nacos
  returnUrl: http://malldev.huhp.cc/#/pages/money/paySuccess
  notifyUrl: http://malldev.huhp.cc/admin/pay/notify
