spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: mall
    password: asd51735
  data:
    mongodb:
      host: mongo
      port: 27017
      database: mall-port
    redis:
      host: redis # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /mall
    username: mall
    password: asd51735
# 日志配置
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: logstash
alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: 9021000140641310
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo5y3NHKNVHq03+rJYNu7fxKmeaLZQ4aYlQ1gl2StSyIULyKxXS4dYW9QKjiZhoihyeuEdzlOgdvbziRCmd47cti9UMStccI3haUXTloQQGSYdav6l7sVN70NVOTabAAFiJJ3SASZViBJlWqvrrwl+R79old2RoSKw9LAnAnFoOzojneyzlx8OpCxDgLhT+lpYCkKBqzwPR1FEapZ4jUNtOm97XA47ye0FGvEjZVnpuhkSyZu4yIfHyMTqt5cLFPNJzRxQZKV+yLt0RzbV4f0o1bSW4it+P5x8qGiOeyEGMW7WfmSVkttM42t9pKleQI3ETFmaM7jcSo+keEVDakGtwIDAQAB
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCjnLc0co1UerTf6slg27t/EqZ5otlDhpiVDWCXZK1LIhQvIrFdLh1hb1AqOJmGiKHJ64R3OU6B29vOJEKZ3jty2L1QxK1xwjeFpRdOWhBAZJh1q/qXuxU3vQ1U5NpsAAWIkndIBJlWIEmVaq+uvCX5Hv2iV3ZGhIrD0sCcCcWg7OiOd7LOXHw6kLEOAuFP6WlgKQoGrPA9HUURqlniNQ206b3tcDjvJ7QUa8SNlWem6GRLJm7jIh8fIxOq3lwsU80nNHFBkpX7Iu3RHNtXh/SjVtJbiK34/nHyoaI57IQYxbtZ+ZJWS20zja32kqV5AjcRMWZozuNxKj6R4RUNqQa3AgMBAAECggEAJ31J0sTbS8qaIXl/xXsDlDYiLDWcDupLpZ4m9CN+mCXPjVjoSj85JC1Dwg0LMSeFNUE9JbGVO06fjO+/i3fSDXQ2rWnrGwvvbrhcGbMvPPuKuMwbncev5VYiA52BApQ2wbHoTF+fyuPcHs4zPQ94ctqCCU7m4zpWa9FQX9kT9DUWtEIeXg7XlLM2p9vzX9q889u9cVLa4UXsFbslk1imyn7hA2OEqtUZfJ1J4NnVuzYuWwu0k4IoNkPA3epR3sHGY1swe1MB0Z4FdQbcxCSzsxhsxMSTBMQhTiWs3BXyq1mVOBunqMo00uZA0DQFM20Qrh1P7hmNJy4jKCxCpV6fAQKBgQDlZqG/qtjiymhqo+hPDJFcffh0B8eefnU51DrSDgnNJt6eHVl8ou0QgU+XbiwUNiTWYfIL13btrlR4uHm+2OwVOMzDO04duGmcsSQIx/gs3bSqPOAPUYQrCrPSP1VKtGceLVkMelCiGuFBAr+WuTQ8hQJ8iIVlZbtNtDPx4AZC9wKBgQC2lUJfgSsDc4sKc4NcDKwY8n39VIE7zAs6/Rmi+kuFYihUDP9Eh6DiiRA5c+WkickxgyWRgbQhmxSZbk/F3Z+AsV2NGQRUc4mnTe37hcuI2f2yNywJvSVPMA/QqZeqRXQxv9LLYQPc2T8wBzMSQQOcbyYsZvrArc296dLl2LaqQQKBgH9Gfw2Bc834cRBhmj1pgqjnd1ahDl7gWJfaKTxr74I0Q6VEMWcWWiMjK46f4LLiC3QqaYmqZOCgLVvBNkLtxaZMmkbje4a/z1DRc2Wv1QDHjTo6hjHZj1P2HyjSXLcS+ndiv5pNrrkR4tIX/UZZwSKmxWdks2Y7mD0Xcw6Ktc6nAoGAGt+RK1lpqVJiTqF93hiHZAyc+qJrew+nP4FtOo24e+NcqDJZiA6mYXFnD+29CSC2mjEBYI9EogWfXI3d8/OQvHJeoJvkBUIUKqnPs0uYD4Z2TrrMIorSaPtb+IxdpFQgrAndzs1yshjPshP9MlybWXUKm1J06dMrCx7VSbtB94ECgYAQYT5ep8zM2AbDZBK+khq0z+EIrfsgNptis+shjdZXZIzHPwGzylqmG7YXUQO7qyVJZR4jEc/+ibnQedE1tLo9P1h830gMMRkIJQ9QNhKa/xuBO7vWlGo6KP+ktU9uCGdDjvTOl/1rQ2ki9U2GaAxr6kpRV160JsjD7NZphLh8ww==
  returnUrl: http://malldev.huhp.cc/#/pages/money/paySuccess
  notifyUrl: http://malldev.huhp.cc/admin/pay/notify
